### PR TITLE
Scan self-deliminating arrays, procedures, and dicts

### LINKED ISSUE #18: Arrays, Procedures, and Dictionaries
Jerry-rigging names doesn't work. Add scan support for arrays, procedures, and dictionaries.

- [ ] Arrays
- [ ] Procedures
- [ ] Dictionaries

### PR DESCRIPTION
**Pull request by ian-shakespeare**
Closes #18

### CODE REVIEW

File: src/scanner.rs [hunk 1]
```diff
@@ -40,31 +47,44 @@ where
...
+                    '(' => return Some(self.read_string_literal()),
+                    '<' => {
+                        return Some(match self.input.next() {
                             None => Err(Error::from(ErrorKind::UnterminatedString)),
                             Some('~') => self.read_string_base85(),
+                            Some('<') => Ok(Token::Name(String::from("<<"))),
                             Some(next_ch) => {
                                 word.push(next_ch);
                                 self.read_string_hex(word)
                             }
```
Comment (ian-shakespeare) [inline src/scanner.rs]: What if a name such as `<!F` is submitted? Would this not try to process it as a string?

File: src/scanner.rs [hunk 2]
```diff
@@ -92,8 +112,42 @@ where
...
+                        word.push(ch);
+                        return self.read_name(word);
+                    }
+                    _ => {
+                        word.push('>');
+                        return self.read_name(word);
+                    }
+                },
                 Some(ch) => match ch {
                     '\0' | ' ' | '\t' | '\r' | '\n' | '\x08' | '\x0C' => break,
```
Comment (ian-shakespeare) [inline src/scanner.rs]: Move this case up a level (don't need the `ch` variable)

File: src/scanner.rs [hunk 3]
```diff
@@ -126,13 +182,47 @@ where
...
+                        word.push(ch);
+                        return self.read_name(word);
+                    }
+                    _ => {
+                        word.push('>');
+                        return self.read_name(word);
+                    }
+                },
                 Some(ch) => match ch {
                     '\0' | ' ' | '\t' | '\r' | '\n' | '\x08' | '\x0C' => {
```
Comment (ian-shakespeare) [inline src/scanner.rs]: Move up a level

File: src/scanner.rs [hunk 4]
```diff
@@ -182,13 +272,47 @@ where
...
```
Comment (ian-shakespeare) [inline src/scanner.rs]: Move up a level

File: src/scanner.rs [hunk 5]
```diff
@@ -324,8 +448,34 @@ where
...
+                        break;
+                    }
+                    Some(ch) => {
+                        word.push('>');
+                        word.push(ch);
+                    }
+                    _ => word.push('>'),
+                },
                 Some(ch) => match ch {
                     '\0' | ' ' | '\t' | '\r' | '\n' | '\x08' | '\x0C' => break,
```
Comment (ian-shakespeare) [inline src/scanner.rs]: Move up a level
